//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Project.Areas.UserArea
{
    using System;
    using System.Collections.Generic;
    
    public partial class MfgTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MfgTbl()
        {
            this.ProductTbls = new HashSet<ProductTbl>();
        }
    
        public long MfgID { get; set; }
        public string MfgName { get; set; }
        public string Address { get; set; }
        public string EmailID { get; set; }
        public string WebsiteUrl { get; set; }
        public string ContactPersonName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductTbl> ProductTbls { get; set; }
    }
}
