//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Project.Areas.UserArea
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Mini_Project_DbFirstEntities : DbContext
    {
        public Mini_Project_DbFirstEntities()
            : base("name=Mini_Project_DbFirstEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryTbl> CategoryTbls { get; set; }
        public virtual DbSet<ColorTbl> ColorTbls { get; set; }
        public virtual DbSet<MfgTbl> MfgTbls { get; set; }
        public virtual DbSet<ProductColorTbl> ProductColorTbls { get; set; }
        public virtual DbSet<ProductTbl> ProductTbls { get; set; }
        public virtual DbSet<UserTbl> UserTbls { get; set; }
    }
}
