//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Project.Areas.UserArea
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductColorTbl
    {
        public long ProductColorID { get; set; }
        public long ProductID { get; set; }
        public long ColorID { get; set; }
    
        public virtual ColorTbl ColorTbl { get; set; }
        public virtual ProductTbl ProductTbl { get; set; }
    }
}
