//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Project.Areas.UserArea
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTbl()
        {
            this.ProductColorTbls = new HashSet<ProductColorTbl>();
        }
    
        public long ProductID { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public long MfgID { get; set; }
        public string ProductDescription { get; set; }
        public long CategoryID { get; set; }
    
        public virtual CategoryTbl CategoryTbl { get; set; }
        public virtual MfgTbl MfgTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductColorTbl> ProductColorTbls { get; set; }
    }
}
